//
// Created by raingoloss on 05/05/2020.
//

#ifndef MFF_VECTOR_DRAWING_PROJECTS_RUNNER_CANVAS_SVG_XML_H
#define MFF_VECTOR_DRAWING_PROJECTS_RUNNER_CANVAS_SVG_XML_H

#endif //MFF_VECTOR_DRAWING_PROJECTS_RUNNER_CANVAS_SVG_XML_H
